### ISSUE TITLE
Is this what I need?

### ISSUE THREAD

**Issue by maximih** [hbldh/pybankid#11]
Hi guys

I am looking into a way to automatically connect to Göteborg Energi user portal and download some statistics. They don't seem to provide an api and are using BankId for authentication.

I have found `pybankid` and I am wondering if it can help me to automate the authentication part. So I would like to have a cronjob or something that logins regularly to Göteborg Energi portal, without any kind of interaction from my side (e.g. without opening MobileBankId app and enter the password).

I currently have BankId on a smartcard (can I use it with `pybankid`?) and Mobile BankId but I can try to request certificates files if that is a must.

I would highly appreciate your help here 

Thanks a lot

//Max

**Comment by hbldh** [comment]
Hello Max,

No, `pybankid` is not what you are looking for. It is e.g. for building websites that provide authentication by BankID. It is not a end-user client where you can sign; those are provided solely by BankID people.

I am pretty sure no automated BankID solution exists. It kind of defeats the purpose of BankID. 
If you want to automate it then I think you would do best in using the desktop client and using some kind of screen manipulation software for sending fake keyboard input to the BankID popup.

Send a mail to Göteborgs Energi and ask for an API instead.
