### ISSUE TITLE
Support Signature Verification

### ISSUE THREAD

**Issue by sheepsy90** [hbldh/pybankid#15]
Hey,

I read that in issue https://github.com/hbldh/pybankid/issues/5 the decision was made to not include signature verification. I however would like to challenge that again and maybe we can come up with an extension to this library.

I have contacted BankID and got the necessary certificate, however the documentation on their site is very sparse and it makes it very complicated, especially as I am not an expert in all the details about certificates.

**My goal:**

Having a discussion again if it should be part of this library, otherwise provide a working  guide with coding examples to include a step by step guide that at least gives more instructions to users of this library (maybe in a readme)

**Comment by sheepsy90** [comment]
Thanks for the starting points. I need to build something that allows us to verify signatures and gives a guide to do this so I will give it a shot. It must be possible somehow.

Will read through the links you provided. Sadly the same as you my knowledge about this is limited.

**Comment by sheepsy90** [comment]
I found my mistake. I gave the wrong data to the signature algorithm. Now need to verify the OCSP response and then I think I have a workable solution.

**Comment by sheepsy90** [comment]
I found my mistake. I gave the wrong data to the signature algorithm. Now need to verify the OCSP response and then I think I have a workable solution.

**Comment by sheepsy90** [comment]
@hbldh I have a script that does all the necessary verification in python. It is definitely a little hacky and rather experimental. However it works and I am reasonable confident that it would be a very good resource and starting point for anyone trying to do something with that.

Maybe we can create an experimental part of the package. That would at least put the code into a logical place.

It currently requires the  **asn1crypto** and **pyOpenSSL**

Maybe someone more sophisticated can reduce this.

**Comment by hbldh** [comment]
I would gladly take a look at it and maybe include it in e.g. an examples folder. When it has been cleaned up and has tests, maybe it can be included as a separate module in pybankid.

**Comment by sheepsy90** [comment]
I will prepare it and also mark everything with TODOs and unsureness markers of things that are definetly not pretty. My main thought here is that it doesn't just lie in my repository after a couple full days of works.

**Comment by johnTunell** [comment]
Has this script been added to the repo? Would like to have a look at it.

**Comment by hbldh** [comment]
Merged #16 so I am closing this. Thank you very much, and sorry for taking so long to handle this...
