### ISSUE TITLE
Support setting requests timeout

### ISSUE THREAD

**Issue by Majsvaffla** [hbldh/pybankid#20]
I think that the clients should have a timeout setting. The *requests* library *Session* class (which is used by the clients already) supports a keyword argument *timeout* to it's *request* method. If the server hasn't responded within *timeout* seconds *requests* raises an exception.

Requests to the BankID service most likely won't time out very often but there should still be a way to handle time outs. Implementing it should be easy since *requests* already supports it. I think the timeout setting should be passed to the BankID client on instantiation. The same timeout setting would be used for all requests sent by that instance.

I am happy to open a pull request if the addition seems like a good idea to you 😃

**Comment by Majsvaffla** [comment]
I found out that the SOAP client already has a default timeout value through *zeep*. Maybe we could skip implementing the timeout setting there since it is deprecated already. The JSON client still lacks a default timeout though and definitely should have one.

**Comment by hbldh** [comment]
Good idea! I am unavailable the rest of this week, but I will definitely look at this next week. Feel free to implement and send in a PR on how you want it to work in the meantime!
My preference is either as a keyword argument direct to the client or as an environment variable, by I am favoring the first option in this case I think.

**Comment by Majsvaffla** [comment]
Good to hear 😄 I will stick with the keyword argument approach. I will open the PR this week.
