### ISSUE TITLE
Old certificate link with pip installation

### ISSUE THREAD

**Issue by kennethschoultz** [hbldh/pybankid#32]
When installing with pip I got the old BankID cerificate link in certutils.py
So: https://www.bankid.com/assets/bankid/rp/FPTestcert2_20150818_102329.pfx
Instead of the current: https://www.bankid.com/assets/bankid/rp/FPTestcert3_20200618.p12
At least when installing Flask-PyBankId

**Comment by hbldh** [comment]
That is because I have not made a release of PyBankID including the testcert link update in https://github.com/hbldh/pybankid/commit/881466d994124e48e731257c0ac917d7843012ca. It only exists in the `master` branch in the Github repo so far.

**Comment by tiwilliam** [comment]
I would be grateful for a new 0.10.4 release with this fix. 🙏

**Comment by hbldh** [comment]
The changes is included in 4c28849 and was just now uploaded as version 0.10.4 to PyPI. Good luck!
