### ISSUE TITLE
Switch to v5.1 endpoint

### ISSUE THREAD

**Issue by Majsvaffla** [hbldh/pybankid#39]
The [latest RP guidelines](https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v3.5.pdf) states that the EOL for the v5 API endpoint is april 2022. The v5.1 endpoint has been available since april 2020. pybankid should switch to use the new endpoint well before the EOL of v5.

**Comment by hbldh** [comment]
Version 0.12.0 is now pushed to PyPI, using the 5.1 endpoint.
