### ISSUE TITLE
Test certificate expired

### ISSUE THREAD

**Issue by dhalenok** [hbldh/pybankid#42]
Pybankid seems to be using an outdated certificate (`https://www.bankid.com/assets/bankid/rp/FPTestcert3_20200618.p12`), while the current one is `https://www.bankid.com/assets/bankid/rp/FPTestcert4_20220818.p12`.

I will try to provide a PR shortly.

**Comment by hbldh** [comment]
Thank you!

**Comment by dhalenok** [comment]
@hbldh Would it be possible to release these changes on PyPI?

**Comment by hbldh** [comment]
I thought I had that automated in commits. Sorry, will remedy it tomorrow.

**Comment by dotchetter** [comment]
How did it go with the pypi release?
