### ISSUE TITLE
Support for async client

### ISSUE THREAD

**Issue by tiwilliam** [hbldh/pybankid#53]
I have a new use case in a fully asynchronous framework currently using httpx. Opening up here for discussion. Would an async API and more modular HTTP backend would be welcomed as a contribution? And if so, any design preferences for how that would work?

**Comment by hbldh** [comment]
Hello, yes that would be greatly appreciated. I also believe that httpx would be best suited. It is something I have put up doing for a long time...

Converting the current client to an async one would be a quite straightforward task, but it is a BankID v5.1 client, so if you are up to the task, it would be good to have it in v6 instead.
