### ISSUE TITLE
Upgrading to API v. 6.0

### ISSUE THREAD

**Issue by mxamin** [hbldh/pybankid#56]
Opening an issue since I don't see any development/discussion on upgrading to v. 6.0 which was released May 2023.
I was planning to start working on that, and I was wondering if anyone has already started or has any ideas so we can sync with each other.

**Comment by mxamin** [comment]
@hbldh Sounds good, I closed the PR and created a new one pointing to `develop` branch. Let me know if I can be of assistance :)

**Comment by nnew2** [comment]
Is there an estimated time on your end for the release that supports RP 6.0? We're approx. 40 days away from the enforcement of "Säker start".

**Comment by hbldh** [comment]
@nnew2 @mxamin There are now working v6 sync and async clients implemented in the `develop` branchs latest commit. As soon as I finish the documentation i will push it to PyPI, but you can start using the existing code if you want to start right away.

**Comment by hbldh** [comment]
Version 1.0.0 of PyBankID, with async and sync clients integrating with the v6 BankID API, has now been officially released and is available on PyPI.
