### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by kirillegrv** [hbldh/pybankid#6]
Hello, guys!
I have a little question about your client.

For create connect you use certificates:
```python
client = BankIDClient(certificates=('path/to/certificate.pem', 'path/to/key.pem'))
```
Can you tell me, what is the certificates. Do I understand correctly, that i am requesting them from the bank. 

May be you can help me, i have a little problem with Swedish and i'm from Russia.
@Tethik @hbldh

**Comment by hbldh** [comment]
@kirillegrv First of, are you sure that this library is what you need? It is a digital identification tool for people with Swedish ID numbers.

Certificates are obtained by [signing an agreement with one of the banks selling BankID](https://www.bankid.com/en/om_bankid/bankid-in-my-services). 
One can test this package by using a [test certificate](https://www.bankid.com/assets/bankid/rp/FPTestcert2_20150818_102329.pfx) from [BankID:s developement pages](https://www.bankid.com/bankid-i-dina-tjanster/rp-info) (see [tests](https://github.com/hbldh/pybankid/blob/master/tests/test_client.py) and [test certificate obtaining code](https://github.com/hbldh/pybankid/blob/master/bankid/testcert.py)).

**Comment by kirillegrv** [comment]
@hbldh Yes, i have the task about auth users on the site over BankID.

Thanks a lot, very detailed answer, you gave the direction to understand the process.
