### ISSUE TITLE
httpx 0.28.0 breaks authenticate()

### ISSUE THREAD

**Issue by cthart** [hbldh/pybankid#74]
* pybankid version: 1.3.0
* Python version: 3.8.10
* Operating System: Ubuntu 20.04.6 LTS

### Description

sslv3 alert bad certificate on client.authenticate() after upgrading to httpx 0.28.0

### What I Did

Upgraded httpx to the latest version just released, 0.28.0

This results in:
[SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:2649)

on client.authenticate()

Reverting to 0.27.2 fixes the problem.

**Comment by hbldh** [comment]
I saw this issue and was planning on adressing it, but I forgot. Sorry. Yes. Pinning a lower version until I can see why is a good idea.

**Comment by hbldh** [comment]
This is brought to `httpx` attention here: https://github.com/encode/httpx/issues/3441 and a preliminary PR is here: https://github.com/encode/httpx/pull/3442

**Comment by gediminasvenc** [comment]
Im on python 3.8.10, rolled back httpx version to httpx==0.27.2 but I am still getting error when running qrdemo app:

httpx.ReadError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:2635)

Maybe some more dependencies must be downgraded? pip freeze returns this:
anyio==4.5.2
blinker==1.8.2
certifi==2024.8.30
click==8.1.7
exceptiongroup==1.2.2
Flask==2.3.2
Flask-Caching==1.10.1
h11==0.14.0
httpcore==1.0.7
httpx==0.27.2
idna==3.10
importlib-metadata==8.5.0
importlib-resources==6.4.5
itsdangerous==2.2.0
jinja2==3.1.4
MarkupSafe==2.1.5
pybankid==1.4.0
sniffio==1.3.1
typing-extensions==4.12.2
werkzeug==3.0.6
zipp==3.20.2

**Comment by cthart** [comment]
@gediminasvenc Please doublecheck. Did it work previously?

**Comment by hbldh** [comment]
I will check the demo app tomorrow. @gediminasvenc will get back to you.

**Comment by gediminasvenc** [comment]
> This has been one of the strangest bugs so far. I am not sure it ever was httpx that was failing, but rather BankIDs test server. Today I could make authentications with my real Bankid on their production server, with the test certificate. Using the test certificate on the test server however did not work at all, and "bad certificate" errors kept happening. Then it went away suddenly, and it works like it always did, for 0.27, 0.28 and 0.28.1 versions. I have made a small change though, so I am not 100% sure...
> 
> Anyway, @gediminasvenc, the demo app should now work as intended.

Thanks for the update! I will check it out a bit later today

**Comment by cthart** [comment]
This is still broken for me!

I upgraded to httpx 0.28.1 and get the same error as above.

When I revert back to httpx 0.27.2 it starts working again.

This is on the production BankID servers.

**Comment by cthart** [comment]
Can you push 1.4.1 to PyPI so I can install it with pip?

**Comment by hbldh** [comment]
@cthart Sorry, I forgot that crucial part of making a patch... I have uploaded it there now.

**Comment by sherbotlicence** [comment]
I still get errors running through firewalls at my school using anything greater than 0.27.2.

**Comment by hbldh** [comment]
@sherbotlicence On my Windows system I can run the tests on both Python 3.10 and 3.13, using httpx 0.27.2, 0.28.0 and 0.28.1. I cannot reproduce your problem. Do you get the same problem as stated in the description above? 

Open a new issue, fill out your system specs (OS and version, Python version and a `pip freeze` of the installed libraries), the error report and link to this one instead of writing here.
