### ISSUE TITLE
Changes in the BankID Service Interface

### ISSUE THREAD

**Issue by hbldh** [hbldh/pybankid#9]
**Mail regarding new endpoint for production server:**

This information is intended for developers and owners of services using BankID.
To manage a generation shift of the root certificate protecting the service we have introduced a new end point for the service. You need to make changes before 1 June 2019.

- The new end point is appapi2.bankid.com
- The new end point provides the same functionality as the old (appapi.bankid.com).
- The new end point is protected using a new root CA, which is available in our guidelines found at https://www.bankid.com/bankid-i-dina-tjanster/rp-info.

Old integrations must be changed to use the new end point and the new root CA must be in the trust store.
The change must be done before 1 June 2019. The old end point will not work after that date. Preferably, do the change as soon as possible to secure your future BankID usage.

**Comment by hbldh** [comment]
Tasks to be done:

- [ ] Add new certificate
- [ ] Add new url
- [ ] Create legacy server option
- [ ] Document

**Comment by sedrik** [comment]
Whats the status of this issue? I tried the commit with your fixes and it works just fine for our production bankid setup. Will you be making a new release any time soon?

**Comment by hbldh** [comment]
I was supposed to ask someone using it with production certs to try it out before release, but it slipped my mind.
Regarding it as verified thanks to your testimony and release will be done during the week or weekend.
